set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'dracula/tmux'
set -g @dracula-show-powerline true
set -g @dracula-plugins ""
set -g @dracula-left-icon-session "🖥"

# set -g default-terminal "screen-256color"
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on

set -g prefix C-b
unbind C-b
bind C-b send-prefix

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key v switch-client -T session-mode \; display-message "SESSION MODE: 0-9 / a-i to switch, Esc to exit"

bind-key -T session-mode 0 run-shell "$HOME/.config/tmux/scripts/switch-session.sh 10"
bind-key -T session-mode 1 run-shell "$HOME/.config/tmux/scripts/switch-session.sh 1"
bind-key -T session-mode 2 run-shell "$HOME/.config/tmux/scripts/switch-session.sh 2"
bind-key -T session-mode 3 run-shell "$HOME/.config/tmux/scripts/switch-session.sh 3"
bind-key -T session-mode 4 run-shell "$HOME/.config/tmux/scripts/switch-session.sh 4"
bind-key -T session-mode 5 run-shell "$HOME/.config/tmux/scripts/switch-session.sh 5"
bind-key -T session-mode 6 run-shell "$HOME/.config/tmux/scripts/switch-session.sh 6"
bind-key -T session-mode 7 run-shell "$HOME/.config/tmux/scripts/switch-session.sh 7"
bind-key -T session-mode 8 run-shell "$HOME/.config/tmux/scripts/switch-session.sh 8"
bind-key -T session-mode 9 run-shell "$HOME/.config/tmux/scripts/switch-session.sh 9"

bind-key -T session-mode a run-shell "$HOME/.config/tmux/scripts/switch-session.sh 11"
bind-key -T session-mode s run-shell "$HOME/.config/tmux/scripts/switch-session.sh 12"
bind-key -T session-mode d run-shell "$HOME/.config/tmux/scripts/switch-session.sh 13"
bind-key -T session-mode f run-shell "$HOME/.config/tmux/scripts/switch-session.sh 14"
bind-key -T session-mode g run-shell "$HOME/.config/tmux/scripts/switch-session.sh 15"
bind-key -T session-mode h run-shell "$HOME/.config/tmux/scripts/switch-session.sh 16"
bind-key -T session-mode i run-shell "$HOME/.config/tmux/scripts/switch-session.sh 17"
bind-key -T session-mode j run-shell "$HOME/.config/tmux/scripts/switch-session.sh 18"
bind-key -T session-mode k run-shell "$HOME/.config/tmux/scripts/switch-session.sh 19"
bind-key -T session-mode Escape switch-client -l

run '~/.tmux/plugins/tpm/tpm'

set -g status-interval 1
set -g status-right-length 200
set -g status-right "#($HOME/.config/tmux/scripts/sessions-bar.sh)"